// This file is auto-generated by `supabase gen types typescript`
// Run: supabase gen types typescript --local > packages/supabase/src/database.types.ts
// Until you run that command, this is a placeholder that satisfies TypeScript.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          created_at: string
        }
        Insert: {
          id: string
          username: string
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          username?: string
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
        }
      }
      recipes: {
        Row: {
          id: string
          user_id: string
          source_url: string
          title: string | null
          description: string | null
          image_url: string | null
          cook_time_min: number | null
          prep_time_min: number | null
          servings: number | null
          cuisine: string | null
          extraction_status: string
          is_public: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          source_url: string
          title?: string | null
          description?: string | null
          image_url?: string | null
          cook_time_min?: number | null
          prep_time_min?: number | null
          servings?: number | null
          cuisine?: string | null
          extraction_status?: string
          is_public?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['recipes']['Insert']>
      }
      recipe_steps: {
        Row: {
          id: string
          recipe_id: string
          step_number: number
          instruction: string
          image_url: string | null
        }
        Insert: {
          id?: string
          recipe_id: string
          step_number: number
          instruction: string
          image_url?: string | null
        }
        Update: Partial<Database['public']['Tables']['recipe_steps']['Insert']>
      }
      ingredients: {
        Row: {
          id: string
          name: string
          category: string | null
        }
        Insert: { id?: string; name: string; category?: string | null }
        Update: Partial<Database['public']['Tables']['ingredients']['Insert']>
      }
      recipe_ingredients: {
        Row: {
          id: string
          recipe_id: string
          ingredient_id: string
          quantity: number | null
          unit: string | null
          preparation: string | null
          is_optional: boolean
          sort_order: number
        }
        Insert: {
          id?: string
          recipe_id: string
          ingredient_id: string
          quantity?: number | null
          unit?: string | null
          preparation?: string | null
          is_optional?: boolean
          sort_order?: number
        }
        Update: Partial<Database['public']['Tables']['recipe_ingredients']['Insert']>
      }
      cook_logs: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          cooked_at: string
          servings_made: number | null
          rating: number | null
          notes: string | null
          photo_url: string | null
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          cooked_at?: string
          servings_made?: number | null
          rating?: number | null
          notes?: string | null
          photo_url?: string | null
        }
        Update: Partial<Database['public']['Tables']['cook_logs']['Insert']>
      }
      pantry_items: {
        Row: {
          id: string
          user_id: string
          ingredient_id: string
          quantity: number | null
          unit: string | null
          expires_at: string | null
          source: string | null
          cook_log_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          ingredient_id: string
          quantity?: number | null
          unit?: string | null
          expires_at?: string | null
          source?: string | null
          cook_log_id?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['pantry_items']['Insert']>
      }
      extraction_jobs: {
        Row: {
          id: string
          recipe_id: string
          status: string
          attempts: number
          error: string | null
          created_at: string
          started_at: string | null
          completed_at: string | null
        }
        Insert: {
          id?: string
          recipe_id: string
          status?: string
          attempts?: number
          error?: string | null
          created_at?: string
          started_at?: string | null
          completed_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['extraction_jobs']['Insert']>
      }
      follows: {
        Row: {
          follower_id: string
          following_id: string
          created_at: string
        }
        Insert: {
          follower_id: string
          following_id: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['follows']['Insert']>
      }
      tags: {
        Row: { id: string; name: string }
        Insert: { id?: string; name: string }
        Update: Partial<Database['public']['Tables']['tags']['Insert']>
      }
      recipe_tags: {
        Row: { recipe_id: string; tag_id: string }
        Insert: { recipe_id: string; tag_id: string }
        Update: Partial<Database['public']['Tables']['recipe_tags']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
